#permalink: /:categories/:title.html 
permalink: /:title.html 
excerpt_separator: "<!-- more -->"

github: yysue
author: "yysue"
email: xxx#163.com
name: "yysue's Blog"
baseurl: /
url: https://yysue.github.io
domain: yysue.github.io

all_categories: [
  ["android", "Android开发","/android/index.html"], 
  ["about", "关于","/about.html"]
]

paginate: 10 
paginate_path: "index_:num"

index_layout: "index.html"
category_layout: "_layouts/category.html"
tag_layout: "_layouts/tag.html"

#不使用gems库中的jekyll-paginate-category
#使用基于jekyll-paginate改写的的栏目分页插件，所以jekyll-paginate还需要用上。
#gems: [jekyll-paginate,jekyll-paginate-category]
gems: [jekyll-paginate]

collections:
  docs:
    output: true

copyright: []
#timezone: Asia/Shanghai

defaults:
  -
    scope:
      path: "" # 一个空的字符串代表项目中所有的文件
      type: "posts" # 以前的 `post`， 在 Jekyll 2.2 里。
    values:
      layout: "default"

markdown: redcarpet
redcarpet:
    extensions: ["fenced_code_blocks", "autolink", "tables", "strikethrough"]
# highlighter: pygments
highlighter: rouge
# markdown: kramdown
# highlighter:    rouge
# kramdown:
#   input:                     GFM
#   auto_ids:                  true
#   footnote_nr:               1
#   entity_output:             as_char
#   toc_levels:                1..6
#   smart_quotes:              lsquo,rsquo,ldquo,rdquo
#   enable_coderay:            false
#   hard_wrap:                 false
#   syntax_highlighter:        rouge
#   transliterated_header_ids: true
#   footnote_backlink:         "&#8617;&#xfe0e;"
